<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260616190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create DeployLab users, applications, environments and deployment requests.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, full_name VARCHAR(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, repository_url VARCHAR(255) NOT NULL, description TEXT NOT NULL, criticality VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE environment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, name VARCHAR(80) NOT NULL, url VARCHAR(255) NOT NULL, type VARCHAR(30) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4626DE223E030ACD ON environment (application_id)');
        $this->addSql('CREATE TABLE deployment_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, target_environment_id INT NOT NULL, requested_by_id INT NOT NULL, title VARCHAR(160) NOT NULL, description TEXT NOT NULL, status VARCHAR(30) NOT NULL, version VARCHAR(80) NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deployed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EC5439393E030ACD ON deployment_request (application_id)');
        $this->addSql('CREATE INDEX IDX_EC5439392C4435BD ON deployment_request (target_environment_id)');
        $this->addSql('CREATE INDEX IDX_EC5439394DA1E751 ON deployment_request (requested_by_id)');
        $this->addSql('ALTER TABLE environment ADD CONSTRAINT FK_7814D14D3E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deployment_request ADD CONSTRAINT FK_3F0330773E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deployment_request ADD CONSTRAINT FK_3F0330775A091C28 FOREIGN KEY (target_environment_id) REFERENCES environment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deployment_request ADD CONSTRAINT FK_3F03307780B6C86F FOREIGN KEY (requested_by_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE deployment_request DROP CONSTRAINT FK_3F0330773E030ACD');
        $this->addSql('ALTER TABLE deployment_request DROP CONSTRAINT FK_3F0330775A091C28');
        $this->addSql('ALTER TABLE deployment_request DROP CONSTRAINT FK_3F03307780B6C86F');
        $this->addSql('ALTER TABLE environment DROP CONSTRAINT FK_7814D14D3E030ACD');
        $this->addSql('DROP TABLE deployment_request');
        $this->addSql('DROP TABLE environment');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE app_user');
    }
}
