<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260616210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add deployment comments and status activity history.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE deployment_activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, deployment_request_id INT NOT NULL, actor_id INT DEFAULT NULL, old_status VARCHAR(30) DEFAULT NULL, new_status VARCHAR(30) NOT NULL, note VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DEPLOYMENT_ACTIVITY_REQUEST ON deployment_activity (deployment_request_id)');
        $this->addSql('CREATE INDEX IDX_DEPLOYMENT_ACTIVITY_ACTOR ON deployment_activity (actor_id)');
        $this->addSql('CREATE TABLE deployment_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, deployment_request_id INT NOT NULL, author_id INT NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DEPLOYMENT_COMMENT_REQUEST ON deployment_comment (deployment_request_id)');
        $this->addSql('CREATE INDEX IDX_DEPLOYMENT_COMMENT_AUTHOR ON deployment_comment (author_id)');
        $this->addSql('ALTER TABLE deployment_activity ADD CONSTRAINT FK_DEPLOYMENT_ACTIVITY_REQUEST FOREIGN KEY (deployment_request_id) REFERENCES deployment_request (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deployment_activity ADD CONSTRAINT FK_DEPLOYMENT_ACTIVITY_ACTOR FOREIGN KEY (actor_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deployment_comment ADD CONSTRAINT FK_DEPLOYMENT_COMMENT_REQUEST FOREIGN KEY (deployment_request_id) REFERENCES deployment_request (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deployment_comment ADD CONSTRAINT FK_DEPLOYMENT_COMMENT_AUTHOR FOREIGN KEY (author_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE deployment_activity DROP CONSTRAINT FK_DEPLOYMENT_ACTIVITY_REQUEST');
        $this->addSql('ALTER TABLE deployment_activity DROP CONSTRAINT FK_DEPLOYMENT_ACTIVITY_ACTOR');
        $this->addSql('ALTER TABLE deployment_comment DROP CONSTRAINT FK_DEPLOYMENT_COMMENT_REQUEST');
        $this->addSql('ALTER TABLE deployment_comment DROP CONSTRAINT FK_DEPLOYMENT_COMMENT_AUTHOR');
        $this->addSql('DROP TABLE deployment_activity');
        $this->addSql('DROP TABLE deployment_comment');
    }
}
